resolver: lts-8.22

packages:
- '.'
- location:
    git: https://gitlab.imn.htwk-leipzig.de/waldmann/begriff.git
    commit: 39c96629fbf6b5fef18277ecfa3bfe1ac9c791f6
  extra-dep: true

system-ghc: true
compiler-check: newer-minor
