Default: &defaults
  user: yesod
  password: yesod
  host: localhost
  port: 5432
  database: yesod
  poolsize: 1000

Development:
  database: star-exec-presenter_development
  <<: *defaults

Testing:
  database: star-exec-presenter_testing
  <<: *defaults

Staging:
  database: star-exec-presenter_staging
  <<: *defaults

Production:
  database: star-exec-presenter_production
  <<: *defaults
