Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  copyright: Stefan von der Krone, René Muhl, Johannes Waldmann | HTWK | IMN

Development:
  port: 3000
  approot: "http://nfa.imn.htwk-leipzig.de/termcomp-devil"
  <<: *defaults

Testing:
  port: 3001
  <<: *defaults

Staging:
  port: 3002
  <<: *defaults

Production:
  approot: "http://nfa.imn.htwk-leipzig.de/termcomp-devel"
  # approot: "http://termcomp.imn.htwk-leipzig.de"
  <<: *defaults
